"""Training gate (PATHWAY_FORWARD.md row test-suite-overhaul sub-item (2)):
current meshnet/train.py's train() vs the FROZEN ORACLE
meshnet/train.py.published, on NTRAINING_STEPS=1000 steps of the real,
published M1 D1 training data, from the published starting config.

This is a direct current-vs-oracle comparison, not a comparison against a
single committed "one good run" golden curve the way
tests/test_training_golden.py (tier 1, PATHWAY_FORWARD.md row
training-guard) is: the golden file here
(tests/golden/training_gate_reference.json) IS one actual, fresh run of
meshnet/train.py.published itself (generated by
tests/fixtures/training_gate/generate_training_gate_reference.py, never
hand-written), so a pass here means "current code reproduces the frozen
oracle's own per-step loss trace", not merely "reproduces some trusted past
number in a json file". meshnet/train.py.published is never edited.

Why this should pass with TOLERANCE=1e-6 (tight): the 3-dot diff between
meshnet/train.py and meshnet/train.py.published (read in full) shows the
training loop itself (sampling, noise injection, predict_acceleration,
backward, optimizer.step(), the lr schedule, loss logging) is byte-for-byte
unchanged; the only additions are opt-in flags (--seed, --rollout_batch_size,
--rollout_fast, --deterministic) that all default to their legacy value
(None/1/'off'/False) and a resume-checkpoint bookkeeping fix that only
changes what is written to train_state-<step>.pt, not the computation at
the step being logged. With neither side given --seed, both rely on the
SAME global torch/numpy/random RNG streams, seeded identically by the two
CLI wrappers (tests/fixtures/meshnet/seeded_pipeline_cli.py /
tests/fixtures/training_gate/published_pipeline_cli.py) before any torch
call -- so a pass here is not a coincidence, it is the expected consequence
of the diff being behavior-preserving for the unseeded default path. If this
test ever fails, meshnet/train.py's training behaviour has silently
diverged from the paper's own code.

GPU 1, not CPU: see tests/fixtures/training_gate/common.py's module
docstring for why (host was heavily loaded at authoring time, not an idle
box -- a TIMING exception does not apply here since this is a correctness
gate, not a timing measurement).

Runtime: ~3-4 min per side (two full subprocess runs: current + the
reference generation already paid for by the committed golden -- this test
itself only re-runs the CURRENT side). Marked slow + training_gate: not in
the fast local loop; skips (not fails) if the real D1 dataset is not
reachable (see common.require_d1_dataset).

Regeneration (deliberate, reviewed act only -- never to silence a failure
whose cause is not understood, tests/README.md's golden-file policy):
    python3 tests/fixtures/training_gate/generate_training_gate_reference.py
"""
import json
import os

import numpy as np
import pytest

from fixtures.training_gate import common

pytestmark = [pytest.mark.training_gate, pytest.mark.slow]

REFERENCE_PATH = os.path.join(common.REPO_ROOT, "tests", "golden", "training_gate_reference.json")
NTRAINING_STEPS = 1000
# Per-step loss match to ~1e-6 (PATHWAY_FORWARD.md spec, verbatim). Both
# sides run under torch.use_deterministic_algorithms(True, warn_only=True)
# with CUBLAS_WORKSPACE_CONFIG set and an identical fixed global seed, so
# this is the text-round-trip-through-loss_log.txt tolerance, the same
# shape as tier 1's TOLERANCE in test_training_golden.py, not a noise floor.
TOLERANCE = 1e-6


def _run_current(tmp_path, lr_scale=1.0, noise_scale=1.0):
    model_dir = os.path.join(str(tmp_path), "model")
    return common.run_training(model_dir, NTRAINING_STEPS, common.CURRENT_CLI,
                                lr_scale=lr_scale, noise_scale=noise_scale)


def test_training_gate_matches_published_oracle(tmp_path):
    rows = _run_current(tmp_path)

    assert os.path.exists(REFERENCE_PATH), (
        "reference missing; generate it with "
        "tests/fixtures/training_gate/generate_training_gate_reference.py and commit it")
    with open(REFERENCE_PATH) as f:
        reference = json.load(f)

    assert len(rows) == NTRAINING_STEPS + 1, (
        f"expected {NTRAINING_STEPS + 1} logged steps (0..{NTRAINING_STEPS}), got "
        f"{len(rows)} -- loss_report_step=1 (config.json) did not take effect")
    assert [r["step"] for r in rows] == reference["steps"], (
        "logged step numbering diverged from the published oracle's reference -- "
        "the training loop's step bookkeeping changed")

    train_losses = np.array([r["train_loss"] for r in rows])
    valid_losses = np.array([r["valid_loss"] for r in rows])
    assert np.isfinite(train_losses).all(), f"non-finite train loss: {train_losses}"
    assert np.isfinite(valid_losses).all(), f"non-finite valid loss: {valid_losses}"

    ref_train = np.array(reference["train_loss"])
    ref_valid = np.array(reference["valid_loss"])
    np.testing.assert_allclose(
        train_losses, ref_train, rtol=TOLERANCE, atol=TOLERANCE, equal_nan=False,
        err_msg="per-step TRAIN loss on real M1 D1 drifted from meshnet/train.py.published's "
                "own reference trace -- current train() has diverged from the paper's code, or "
                "the reference needs regenerating (see module docstring)")
    np.testing.assert_allclose(
        valid_losses, ref_valid, rtol=TOLERANCE, atol=TOLERANCE, equal_nan=False,
        err_msg="per-step VALID loss on real M1 D1 drifted from meshnet/train.py.published's "
                "own reference trace")
